# Generated by Django 4.1.7 on 2023-03-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botName', models.CharField(max_length=100)),
                ('function', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('botFactory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.factory')),
            ],
        ),
    ]
